### ISSUE TITLE
Request to add github action 

### ISSUE THREAD

**Issue by Jassi10000** [EddieHubCommunity/EddieBotBreakout#17] opened 2021-10-30 05:19 UTC
@eddiejaoude  
This is an awesome and an engaging repository , plus due to hacktoberfest'21 many open source enthusiasts ( preferably students who are first time contributors ) open issues and PRs which eventually help repo to grow
I think there should be a github action to welcome contributors on their each issue and PR too so as to make repository more interactive

If you love the idea , please assign this to me

**Comment by Jassi10000** [comment] 2021-10-30 07:57
@Cahllagerfeld Can you please add the hacktoberfest label to this

**Comment by Jassi10000** [comment] 2021-10-31 08:17
@Cahllagerfeld The label got removed

**Comment by Vyvy-vi** [comment] 2021-11-06 19:42
duplicate of #9

**Comment by Vyvy-vi** [comment] 2021-11-06 19:43
closed by 9584505

**Closed** 2022-01-14 02:23 UTC
Labels: no-issue-activity
